
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit
import ctypes
import Pederson
import mainp
import ctypes


class NewForm(object):

    def __init__(self):
        super (NewForm, self).__init__ ()
        self.lst = []
        self.user_g=""
        self.user_id=""

    def back_Main(self):
        # self.window=QtWidgets.QMainWindow()
        # self.ui= mainp.Ui_MainWindow()
        # self.ui.setupUi(self.window)
        # self.window.show()
        # self.Dialog = QtWidgets.QDialog ()
        # self.ui = NewForm ()
        # self.ui.setupUi(self.Dialog)
        # Dialog.hide()
        pass

    def save_RButton(self):
        count=1
        total_iter=1
        for i in self.lst:
            count+=1
            if count%8==0:
                total_iter+=0
                if total_iter==8: break;
            if (i.isChecked()):
                  # print((i).text())
                  self.user_g+=(i).text()
        self.user_g=self.user_g[::-1]
        # print(self.user_g[::-1])
        for item in (self.id_input).text():
            self.user_id+=item
        # print(self.user_id)
        if len(self.user_g)==8:
            if self.user_id is not 0:

                print("geuss:",self.user_g)
                print("id:",self.user_id)
                text=Pederson.commit(int(self.user_id),int(self.user_g))
                # ctypes.windll.user32.MessageBoxW(0, text,
                #                              "Form Launched", 1)

                MessageBox = ctypes.windll.user32.MessageBoxW
                MessageBox(None,text, 'Confirm', 0)

        # sys.exit()
             # self.connect(self.back_Main)

        else:
            self.user_g=""
            self.user_id= ""
            ctypes.windll.user32.MessageBoxW (0, "Error!Please complete the form.\n",
                                          "Form Launched", 1)
            # back_Main(self)





    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(454, 288)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        self.formLayout_2 = QtWidgets.QFormLayout(Dialog)
        self.formLayout_2.setObjectName("formLayout_2")
        self.welcome_lable = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.welcome_lable.sizePolicy().hasHeightForWidth())
        self.welcome_lable.setSizePolicy(sizePolicy)
        self.welcome_lable.setObjectName("welcome_lable")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.welcome_lable)
        self.id_lable = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_lable.sizePolicy().hasHeightForWidth())
        self.id_lable.setSizePolicy(sizePolicy)
        self.id_lable.setObjectName("id_lable")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.id_lable)
        self.id_input = QLineEdit(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.id_input.sizePolicy().hasHeightForWidth())
        self.id_input.setSizePolicy(sizePolicy)
        self.id_input.setText("")
        self.id_input.setObjectName("id_input")
        # self.user_id+=(self.id_input).text()
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.id_input)
        self.send_new_form = QtWidgets.QPushButton(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.send_new_form.sizePolicy().hasHeightForWidth())
        self.send_new_form.setSizePolicy(sizePolicy)
        self.send_new_form.setObjectName("send_new_form")

        self.formLayout_2.setWidget(11, QtWidgets.QFormLayout.LabelRole, self.send_new_form)
        self.horizontalGroupBox_8 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_8.setObjectName("horizontalGroupBox_8")
        self.line_8 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_8)
        self.line_8.setObjectName("line_8")
        self.rb_81 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_81.setObjectName("rb_81")
        self.line_8.addWidget(self.rb_81)
        self.lst.append (self.rb_81)
        self.rb_82 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_82.setObjectName("rb_82")
        self.line_8.addWidget(self.rb_82)
        self.lst.append (self.rb_82)
        self.rb_83 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_83.setObjectName("rb_83")
        self.line_8.addWidget(self.rb_83)
        self.lst.append (self.rb_83)
        self.rb_84 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_84.setObjectName("rb_84")
        self.line_8.addWidget(self.rb_84)
        self.lst.append (self.rb_84)
        self.rb_85 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_85.setObjectName("rb_85")
        self.line_8.addWidget(self.rb_85)
        self.lst.append (self.rb_85)
        self.rb_86 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_86.setObjectName("rb_86")
        self.line_8.addWidget(self.rb_86)
        self.lst.append (self.rb_86)
        self.rb_87 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_87.setObjectName("rb_87")
        self.line_8.addWidget(self.rb_87)
        self.lst.append (self.rb_87)
        self.rb_88 = QtWidgets.QRadioButton(self.horizontalGroupBox_8)
        self.rb_88.setObjectName("rb_88")
        self.line_8.addWidget(self.rb_88)
        self.lst.append (self.rb_88)
        self.formLayout_2.setWidget(10, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_8)
        self.horizontalGroupBox_7 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_7.setObjectName("horizontalGroupBox_7")
        self.line_7 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_7)
        self.line_7.setObjectName("line_7")
        self.rb_71 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_71.setObjectName("rb_71")
        self.line_7.addWidget(self.rb_71)
        self.lst.append (self.rb_71)
        self.rb_72 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_72.setObjectName("rb_72")
        self.line_7.addWidget(self.rb_72)
        self.lst.append (self.rb_72)
        self.rb_73 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_73.setObjectName("rb_73")
        self.line_7.addWidget(self.rb_73)
        self.lst.append (self.rb_73)
        self.rb_74 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_74.setObjectName("rb_74")
        self.line_7.addWidget(self.rb_74)
        self.lst.append (self.rb_74)
        self.rb_75 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_75.setObjectName("rb_75")
        self.line_7.addWidget(self.rb_75)
        self.lst.append (self.rb_75)
        self.rb_76 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_76.setObjectName("rb_76")
        self.line_7.addWidget(self.rb_76)
        self.lst.append (self.rb_76)
        self.rb_77 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_77.setObjectName("rb_77")
        self.line_7.addWidget(self.rb_77)
        self.lst.append (self.rb_77)
        self.rb_78 = QtWidgets.QRadioButton(self.horizontalGroupBox_7)
        self.rb_78.setObjectName("rb_78")
        self.line_7.addWidget(self.rb_78)
        self.lst.append (self.rb_78)
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_7)
        self.horizontalGroupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_4.setObjectName("horizontalGroupBox_4")
        self.line_6 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_4)
        self.line_6.setObjectName("line_6")
        self.rb_61 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_61.setObjectName("rb_61")
        self.line_6.addWidget(self.rb_61)
        self.lst.append (self.rb_61)
        self.rb_62 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_62.setObjectName("rb_62")
        self.line_6.addWidget(self.rb_62)
        self.lst.append (self.rb_62)
        self.rb_63 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_63.setObjectName("rb_63")
        self.line_6.addWidget(self.rb_63)
        self.lst.append (self.rb_63)
        self.rb_64 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_64.setObjectName("rb_64")
        self.line_6.addWidget(self.rb_64)
        self.lst.append (self.rb_64)
        self.rb_65 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_65.setObjectName("rb_65")
        self.line_6.addWidget(self.rb_65)
        self.lst.append (self.rb_65)
        self.rb_66 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_66.setObjectName("rb_66")
        self.line_6.addWidget(self.rb_66)
        self.lst.append (self.rb_66)
        self.rb_67 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_67.setObjectName("rb_67")
        self.line_6.addWidget(self.rb_67)
        self.lst.append (self.rb_67)
        self.rb_68 = QtWidgets.QRadioButton(self.horizontalGroupBox_4)
        self.rb_68.setObjectName("rb_68")
        self.line_6.addWidget(self.rb_68)
        self.lst.append (self.rb_68)
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_4)
        self.horizontalGroupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_5.setObjectName("horizontalGroupBox_5")
        self.line_5 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_5)
        self.line_5.setObjectName("line_5")
        self.rb_51 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_51.setObjectName("rb_51")
        self.line_5.addWidget(self.rb_51)
        self.lst.append (self.rb_51)
        self.rb_52 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_52.setObjectName("rb_52")
        self.line_5.addWidget(self.rb_52)
        self.lst.append (self.rb_52)
        self.rb_53 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_53.setObjectName("rb_53")
        self.line_5.addWidget(self.rb_53)
        self.lst.append (self.rb_53)
        self.rb_54 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_54.setObjectName("rb_54")
        self.line_5.addWidget(self.rb_54)
        self.lst.append (self.rb_54)
        self.rb_55 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_55.setObjectName("rb_55")
        self.line_5.addWidget(self.rb_55)
        self.lst.append (self.rb_55)
        self.rb_56 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_56.setObjectName("rb_56")
        self.line_5.addWidget(self.rb_56)
        self.lst.append (self.rb_56)
        self.rb_57 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_57.setObjectName("rb_57")
        self.line_5.addWidget(self.rb_57)
        self.lst.append (self.rb_57)
        self.rb_58 = QtWidgets.QRadioButton(self.horizontalGroupBox_5)
        self.rb_58.setObjectName("rb_58")
        self.line_5.addWidget(self.rb_58)
        self.lst.append (self.rb_58)
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_5)
        self.horizontalGroupBox_6 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_6.setObjectName("horizontalGroupBox_6")
        self.line_4 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_6)
        self.line_4.setObjectName("line_4")
        self.rb_41 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_41.setObjectName("rb_41")
        self.line_4.addWidget(self.rb_41)
        self.lst.append (self.rb_41)
        self.rb_42 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_42.setObjectName("rb_42")
        self.line_4.addWidget(self.rb_42)
        self.lst.append (self.rb_42)
        self.rb_43 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_43.setObjectName("rb_43")
        self.line_4.addWidget(self.rb_43)
        self.lst.append (self.rb_43)
        self.rb_44 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_44.setObjectName("rb_44")
        self.line_4.addWidget(self.rb_44)
        self.lst.append (self.rb_44)
        self.rb_45 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_45.setObjectName("rb_45")
        self.line_4.addWidget(self.rb_45)
        self.lst.append (self.rb_45)
        self.rb_46 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_46.setObjectName("rb_46")
        self.line_4.addWidget(self.rb_46)
        self.lst.append (self.rb_46)
        self.rb_47 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_47.setObjectName("rb_47")
        self.line_4.addWidget(self.rb_47)
        self.lst.append (self.rb_47)
        self.rb_48 = QtWidgets.QRadioButton(self.horizontalGroupBox_6)
        self.rb_48.setObjectName("rb_48")
        self.line_4.addWidget(self.rb_48)
        self.lst.append (self.rb_48)
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_6)
        self.horizontalGroupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_3.setObjectName("horizontalGroupBox_3")
        self.line_3 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_3)
        self.line_3.setObjectName("line_3")
        self.rb_31 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_31.setObjectName("rb_31")
        self.line_3.addWidget(self.rb_31)
        self.lst.append (self.rb_31)
        self.rb_32 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_32.setObjectName("rb_32")
        self.line_3.addWidget(self.rb_32)
        self.lst.append (self.rb_32)
        self.rb_33 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_33.setObjectName("rb_33")
        self.line_3.addWidget(self.rb_33)
        self.lst.append (self.rb_33)
        self.rb_34 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_34.setObjectName("rb_34")
        self.line_3.addWidget(self.rb_34)
        self.lst.append (self.rb_34)
        self.rb_35 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_35.setObjectName("rb_35")
        self.line_3.addWidget(self.rb_35)
        self.lst.append (self.rb_35)
        self.rb_36 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_36.setObjectName("rb_36")
        self.line_3.addWidget(self.rb_36)
        self.lst.append (self.rb_36)
        self.rb_37 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_37.setObjectName("rb_37")
        self.line_3.addWidget(self.rb_37)
        self.lst.append (self.rb_37)
        self.rb_38 = QtWidgets.QRadioButton(self.horizontalGroupBox_3)
        self.rb_38.setObjectName("rb_38")
        self.line_3.addWidget(self.rb_38)
        self.lst.append (self.rb_38)
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_3)
        self.horizontalGroupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox_2.setObjectName("horizontalGroupBox_2")
        self.line_2 = QtWidgets.QHBoxLayout(self.horizontalGroupBox_2)
        self.line_2.setObjectName("line_2")
        self.rb_21 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_21.setObjectName("rb_21")
        self.line_2.addWidget(self.rb_21)
        self.lst.append (self.rb_21)
        self.rb_22 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_22.setObjectName("rb_22")
        self.line_2.addWidget(self.rb_22)
        self.lst.append (self.rb_22)
        self.rb_23 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_23.setObjectName("rb_23")
        self.line_2.addWidget(self.rb_23)
        self.lst.append (self.rb_23)
        self.rb_24 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_24.setObjectName("rb_24")
        self.line_2.addWidget(self.rb_24)
        self.lst.append (self.rb_24)
        self.rb_25 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_25.setObjectName("rb_25")
        self.line_2.addWidget(self.rb_25)
        self.lst.append (self.rb_25)
        self.rb_26 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_26.setObjectName("rb_26")
        self.line_2.addWidget(self.rb_26)
        self.lst.append (self.rb_26)
        self.rb_27 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_27.setObjectName("rb_27")
        self.line_2.addWidget(self.rb_27)
        self.lst.append (self.rb_27)
        self.rb_28 = QtWidgets.QRadioButton(self.horizontalGroupBox_2)
        self.rb_28.setObjectName("rb_28")
        self.line_2.addWidget(self.rb_28)
        self.lst.append (self.rb_28)
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox_2)
        self.horizontalGroupBox = QtWidgets.QGroupBox(Dialog)
        self.horizontalGroupBox.setObjectName("horizontalGroupBox")
        self.line_1 = QtWidgets.QHBoxLayout(self.horizontalGroupBox)
        self.line_1.setObjectName("line_1")
        self.rb_11 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_11.sizePolicy().hasHeightForWidth())
        self.rb_11.setSizePolicy(sizePolicy)
        self.rb_11.setObjectName("rb_11")
        self.line_1.addWidget(self.rb_11)
        self.lst.append (self.rb_11)
        self.rb_12 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_12.sizePolicy().hasHeightForWidth())
        self.rb_12.setSizePolicy(sizePolicy)
        self.rb_12.setObjectName("rb_12")
        self.line_1.addWidget(self.rb_12)
        self.lst.append (self.rb_12)
        self.rb_13 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_13.sizePolicy().hasHeightForWidth())
        self.rb_13.setSizePolicy(sizePolicy)
        self.rb_13.setObjectName("rb_13")
        self.line_1.addWidget(self.rb_13)
        self.lst.append (self.rb_13)
        self.rb_14 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_14.sizePolicy().hasHeightForWidth())
        self.rb_14.setSizePolicy(sizePolicy)
        self.rb_14.setObjectName("rb_14")
        self.line_1.addWidget(self.rb_14)
        self.lst.append (self.rb_14)
        self.rb_15 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_15.sizePolicy().hasHeightForWidth())
        self.rb_15.setSizePolicy(sizePolicy)
        self.rb_15.setObjectName("rb_15")
        self.line_1.addWidget(self.rb_15)
        self.lst.append (self.rb_15)
        self.rb_16 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_16.sizePolicy().hasHeightForWidth())
        self.rb_16.setSizePolicy(sizePolicy)
        self.rb_16.setObjectName("rb_16")
        self.line_1.addWidget(self.rb_16)
        self.lst.append (self.rb_16)
        self.rb_17 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_17.sizePolicy().hasHeightForWidth())
        self.rb_17.setSizePolicy(sizePolicy)
        self.rb_17.setObjectName("rb_17")
        self.line_1.addWidget(self.rb_17)
        self.lst.append (self.rb_17)
        self.rb_18 = QtWidgets.QRadioButton(self.horizontalGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rb_18.sizePolicy().hasHeightForWidth())
        self.rb_18.setSizePolicy(sizePolicy)
        self.rb_18.setObjectName("rb_18")
        self.line_1.addWidget(self.rb_18)
        self.lst.append (self.rb_18)
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.SpanningRole, self.horizontalGroupBox)
        self.send_new_form.clicked.connect (self.save_RButton)


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "New Lottery Form"))
        self.welcome_lable.setText(_translate("Dialog", "WELCOME!"))
        self.id_lable.setText(_translate("Dialog", "Please Enter Your ID: "))
        self.send_new_form.setText(_translate("Dialog", "Send ! "))
        self.rb_81.setText(_translate("Dialog", "1"))
        self.rb_82.setText(_translate("Dialog", "2"))
        self.rb_83.setText(_translate("Dialog", "3"))
        self.rb_84.setText(_translate("Dialog", "4"))
        self.rb_85.setText(_translate("Dialog", "5"))
        self.rb_86.setText(_translate("Dialog", "6"))
        self.rb_87.setText(_translate("Dialog", "7"))
        self.rb_88.setText(_translate("Dialog", "8"))
        self.rb_71.setText(_translate("Dialog", "1"))
        self.rb_72.setText(_translate("Dialog", "2"))
        self.rb_73.setText(_translate("Dialog", "3"))
        self.rb_74.setText(_translate("Dialog", "4"))
        self.rb_75.setText(_translate("Dialog", "5"))
        self.rb_76.setText(_translate("Dialog", "6"))
        self.rb_77.setText(_translate("Dialog", "7"))
        self.rb_78.setText(_translate("Dialog", "8"))
        self.rb_61.setText(_translate("Dialog", "1"))
        self.rb_62.setText(_translate("Dialog", "2"))
        self.rb_63.setText(_translate("Dialog", "3"))
        self.rb_64.setText(_translate("Dialog", "4"))
        self.rb_65.setText(_translate("Dialog", "5"))
        self.rb_66.setText(_translate("Dialog", "6"))
        self.rb_67.setText(_translate("Dialog", "7"))
        self.rb_68.setText(_translate("Dialog", "8"))
        self.rb_51.setText(_translate("Dialog", "1"))
        self.rb_52.setText(_translate("Dialog", "2"))
        self.rb_53.setText(_translate("Dialog", "3"))
        self.rb_54.setText(_translate("Dialog", "4"))
        self.rb_55.setText(_translate("Dialog", "5"))
        self.rb_56.setText(_translate("Dialog", "6"))
        self.rb_57.setText(_translate("Dialog", "7"))
        self.rb_58.setText(_translate("Dialog", "8"))
        self.rb_41.setText(_translate("Dialog", "1"))
        self.rb_42.setText(_translate("Dialog", "2"))
        self.rb_43.setText(_translate("Dialog", "3"))
        self.rb_44.setText(_translate("Dialog", "4"))
        self.rb_45.setText(_translate("Dialog", "5"))
        self.rb_46.setText(_translate("Dialog", "6"))
        self.rb_47.setText(_translate("Dialog", "7"))
        self.rb_48.setText(_translate("Dialog", "8"))
        self.rb_31.setText(_translate("Dialog", "1"))
        self.rb_32.setText(_translate("Dialog", "2"))
        self.rb_33.setText(_translate("Dialog", "3"))
        self.rb_34.setText(_translate("Dialog", "4"))
        self.rb_35.setText(_translate("Dialog", "5"))
        self.rb_36.setText(_translate("Dialog", "6"))
        self.rb_37.setText(_translate("Dialog", "7"))
        self.rb_38.setText(_translate("Dialog", "8"))
        self.rb_21.setText(_translate("Dialog", "1"))
        self.rb_22.setText(_translate("Dialog", "2"))
        self.rb_23.setText(_translate("Dialog", "3"))
        self.rb_24.setText(_translate("Dialog", "4"))
        self.rb_25.setText(_translate("Dialog", "5"))
        self.rb_26.setText(_translate("Dialog", "6"))
        self.rb_27.setText(_translate("Dialog", "7"))
        self.rb_28.setText(_translate("Dialog", "8"))
        self.rb_11.setText(_translate("Dialog", "1"))
        self.rb_12.setText(_translate("Dialog", "2"))
        self.rb_13.setText(_translate("Dialog", "3"))
        self.rb_14.setText(_translate("Dialog", "4"))
        self.rb_15.setText(_translate("Dialog", "5"))
        self.rb_16.setText(_translate("Dialog", "6"))
        self.rb_17.setText(_translate("Dialog", "7"))
        self.rb_18.setText(_translate("Dialog", "8"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = NewForm()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
